// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcNdMZbcaORYCPSX3tew8WXRBMw8K5dEk',
    appId: '1:834956967063:web:4e2a05ce082ee659e43dd2',
    messagingSenderId: '834956967063',
    projectId: 'registeration-988d7',
    authDomain: 'registeration-988d7.firebaseapp.com',
    storageBucket: 'registeration-988d7.firebasestorage.app',
    measurementId: 'G-2655NVN9W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFb21aFxxIg18vwJalXmyfmsZ8MUfGs-E',
    appId: '1:834956967063:android:bd88f38091e305fee43dd2',
    messagingSenderId: '834956967063',
    projectId: 'registeration-988d7',
    storageBucket: 'registeration-988d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtym5SG2L2GCZuj6nvCFBmwAKECe7rf34',
    appId: '1:834956967063:ios:36c3ae10ed2e16abe43dd2',
    messagingSenderId: '834956967063',
    projectId: 'registeration-988d7',
    storageBucket: 'registeration-988d7.firebasestorage.app',
    iosBundleId: 'com.example.registeration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtym5SG2L2GCZuj6nvCFBmwAKECe7rf34',
    appId: '1:834956967063:ios:36c3ae10ed2e16abe43dd2',
    messagingSenderId: '834956967063',
    projectId: 'registeration-988d7',
    storageBucket: 'registeration-988d7.firebasestorage.app',
    iosBundleId: 'com.example.registeration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcNdMZbcaORYCPSX3tew8WXRBMw8K5dEk',
    appId: '1:834956967063:web:5217a703d70d5072e43dd2',
    messagingSenderId: '834956967063',
    projectId: 'registeration-988d7',
    authDomain: 'registeration-988d7.firebaseapp.com',
    storageBucket: 'registeration-988d7.firebasestorage.app',
    measurementId: 'G-PHFJMP85K3',
  );
}
